[package]
name = "telegrambot_ukranian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.192", features = ["derive"] }
teloxide = { version = "0.12.2", features = ["macros", "webhooks-axum"] }
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
url = "2.5.0"
