version: "3.9"
name: telegrambot_ukranian

services:
  telegrambot_ukranian:
    image: ghcr.io/adrianvillanueva997/telegrambot-ukranian:v5.7.0
    container_name: telegrambot_ukranian
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - url=${URL}
      - openweather_key=${OPENWEATHER_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ukranian-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.ukranian-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.ukranian-http.middlewares=ukranian-redirect-https
      - traefik.http.routers.ukranian-http.rule=Host(`ukranian.thexiao77.com`)
      - traefik.http.routers.ukranian-http.entrypoints=http
      - traefik.http.routers.ukranian-https.rule=Host(`ukranian.thexiao77.com`)
      - traefik.http.routers.ukranian-https.tls.certresolver=le
      - traefik.http.routers.ukranian-https.tls=true
      - traefik.http.routers.ukranian-https.entrypoints=https
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
