---
name: telegrambot_ukranian
services:
  telegrambot_ukranian:
    image: ghcr.io/adrianvillanueva997/telegrambot-ukranian:v5.5.0
    networks:
      - proxy
    container_name: telegrambot_ukranian
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ukranian-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.ukranian-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.ukranian-http.middlewares=ukranian-redirect-https
      - traefik.http.routers.ukranian-http.rule=Host(`ukranian.thexiao77.com`)
      - traefik.http.routers.ukranian-http.entrypoints=http
      - traefik.http.routers.ukranian-https.rule=Host(`ukranian.thexiao77.com`)
      - traefik.http.routers.ukranian-https.tls.certresolver=le
      - traefik.http.routers.ukranian-https.tls=true
      - traefik.http.routers.ukranian-https.entrypoints=https
      - traefik.docker.network=proxy
    env_file:
      - stack.env
networks:
  proxy:
    external: true
