version: '3'
services:
  bot:
    restart: unless-stopped
    image: adrianvillanueva997/telegrambot_ukranianmeme
    container_name: telegram_ukranian_PROD
    networks:
      - bots
    env_file:
      - .env
networks:
  bots:
    external: true
