version: "3"
services:
  wikired_api:
    restart: unless-stopped
    image: wikired_api_dev
    container_name: wikired_api
    networks:
      - bots
    ports:
      - 80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  bots:
    external: true
